package com.ciandt.techgallery.sample.service;

import java.util.ArrayList;
import java.util.List;

import com.ciandt.techgallery.sample.persistence.dao.TechnologySampleDAO;
import com.ciandt.techgallery.sample.persistence.dao.TechnologySampleDAOImpl;
import com.ciandt.techgallery.sample.persistence.model.RecommendationSample;
import com.ciandt.techgallery.sample.persistence.model.TechnologySample;
import com.ciandt.techgallery.sample.service.model.RecResponse;
import com.ciandt.techgallery.sample.service.model.Response;
import com.ciandt.techgallery.sample.service.model.TechResponse;
import com.googlecode.objectify.Key;

/**
 * TechnologyServiceImpl methods implementation.
 * 
 * @author Felipe Goncalves de Castro
 *
 */
public class TechServiceImpl extends GenericService<TechResponse, TechnologySample, Long>
    implements TechService {

  RecService recService = new RecService();

  TechnologySampleDAO dao = new TechnologySampleDAOImpl();

  /**
   * Method that add Technology into datastore.
   * 
   * @param technology to be persisted.
   * @return key generated by datastore.
   */
  public TechResponse add(TechResponse response) {
    TechnologySample entity = new TechnologySample();
    entity.setName(response.getName());

    Key<TechnologySample> key = dao.add(entity);

    List<Key<RecommendationSample>> listKeyRec = null;
    if (response.getRecommendationsResponse() != null) {
      listKeyRec = new ArrayList<Key<RecommendationSample>>();

      for (RecResponse recResponse : response.getRecommendationsResponse()) {
        RecommendationSample rec = new RecommendationSample();
        rec.setScore(recResponse.getScore());
        rec.setTechnology(key);

        Key<RecommendationSample> keyRecAtual = recService.add(rec);
        listKeyRec.add(keyRecAtual);
      }
    }

    entity.setRecommendations(listKeyRec);
    dao.update(entity);

    response.setId(entity.getId());

    return response;
  }

  @Override
  public List<Response> listAll() {
    // TODO Auto-generated method stub
    return null;
  }

}
