package com.ciant.techgallery.sample.services;

import java.util.List;

import com.ciandt.techgallery.sample.persistence.dao.RecommendationDAO;
import com.ciandt.techgallery.sample.persistence.dao.RecommendationDAOImpl;
import com.ciandt.techgallery.sample.persistence.model.Recommendation;
import com.googlecode.objectify.Key;

/**
 * RecommendationService methods.
 * 
 * @author Felipe Goncalves de Castro
 *
 */
public class RecommendationService {

  RecommendationDAO dao = new RecommendationDAOImpl();

  /**
   * Method that return the List of Recommendations.
   * 
   * @return list of Recommendations.
   */
  public List<Recommendation> findAll() {
    List<Recommendation> list = dao.findAll();

    return list;
  }

  /**
   * Method that add Recommendation into datastore.
   * 
   * @param recommendation to be persisted.
   * @return key generated by datastore.
   */
  public Key<Recommendation> add(Recommendation entity) {
    Key<Recommendation> key = dao.add(entity);

    return key;
  }
}
