package com.ciant.techgallery.sample.services;

import java.util.List;

import com.ciandt.techgallery.sample.persistence.dao.SampleDAO;
import com.ciandt.techgallery.sample.persistence.dao.SampleDAOImpl;
import com.ciandt.techgallery.sample.persistence.model.Sample;
import com.googlecode.objectify.Key;

/**
 * SampleService methods implementation.
 * 
 * @author felipegc
 *
 */
public class SampleService {

  SampleDAO sampleDAO = new SampleDAOImpl();

  /**
   * Method that return the List of Samples.
   * 
   * @return list of samples.
   */
  public List<Sample> findAll() {
    List<Sample> listSample = sampleDAO.findAll();

    return listSample;
  }

  /**
   * Method that add Sample into datastore.
   * 
   * @param sample to be persisted.
   * @return key generated by datastore.
   */
  public Key<Sample> add(Sample sample) {
    Key<Sample> key = sampleDAO.add(sample);

    return key;
  }

}
