package com.ciant.techgallery.sample.services;

import java.util.ArrayList;
import java.util.List;

import com.ciandt.techgallery.sample.persistence.dao.TechnologyDAO;
import com.ciandt.techgallery.sample.persistence.dao.TechnologyDAOImpl;
import com.ciandt.techgallery.sample.persistence.model.Recommendation;
import com.ciandt.techgallery.sample.persistence.model.Technology;
import com.ciant.techgallery.sample.service.model.RecResponse;
import com.ciant.techgallery.sample.service.model.Response;
import com.ciant.techgallery.sample.service.model.TechResponse;
import com.googlecode.objectify.Key;

/**
 * TechnologyServiceImpl methods implementation.
 * 
 * @author Felipe Goncalves de Castro
 *
 */
public class TechServiceImpl extends GenericService<TechResponse, Technology, Long>
    implements TechService {

  RecService recService = new RecService();

  TechnologyDAO dao = new TechnologyDAOImpl();

  /**
   * Method that add Technology into datastore.
   * 
   * @param technology to be persisted.
   * @return key generated by datastore.
   */
  public TechResponse add(TechResponse entrada) {
    Technology entity = new Technology();
    entity.setName(entrada.getName());

    Key<Technology> key = dao.add(entity);

    List<Key<Recommendation>> listKeyRec = null;
    if (entrada.getRecommendationsResponse() != null) {
      listKeyRec = new ArrayList<Key<Recommendation>>();

      for (RecResponse recResponse : entrada.getRecommendationsResponse()) {
        Recommendation rec = new Recommendation();
        rec.setScore(recResponse.getScore());
        rec.setTechnology(key);

        Key<Recommendation> keyRecAtual = recService.add(rec);
        listKeyRec.add(keyRecAtual);
      }
    }

    entity.setRecommendations(listKeyRec);
    dao.update(entity);

    entrada.setId(entity.getId());

    return entrada;
  }

  @Override
  public List<Response> listAll() {
    // TODO Auto-generated method stub
    return null;
  }

}
