package com.ciant.techgallery.sample.services;

import java.util.ArrayList;
import java.util.List;

import com.ciandt.techgallery.sample.persistence.dao.TechnologyDAO;
import com.ciandt.techgallery.sample.persistence.dao.TechnologyDAOImpl;
import com.ciandt.techgallery.sample.persistence.model.Recommendation;
import com.ciandt.techgallery.sample.persistence.model.Technology;
import com.ciant.techgallery.sample.service.model.RecommendationResponse;
import com.ciant.techgallery.sample.service.model.TechnologyResponse;
import com.ciant.techgallery.sample.services.model.enums.ResponseMensagem;
import com.googlecode.objectify.Key;

public class TechnologyServiceImpl extends GenericService<TechnologyResponse, Technology, Long>
    implements TechnologyService {

  RecommendationService recService = new RecommendationService();

  TechnologyDAO dao = new TechnologyDAOImpl();

  /**
   * Method that add Technology into datastore.
   * 
   * @param technology to be persisted.
   * @return key generated by datastore.
   */
  public TechnologyResponse add(TechnologyResponse entrada) {
    Technology entity = new Technology();
    entity.setName(entrada.getName());

    Key<Technology> key = dao.add(entity);

    List<Key<Recommendation>> listKeyRec = null;
    if (entrada.getRecommendationsPojo() != null) {
      listKeyRec = new ArrayList<Key<Recommendation>>();

      for (RecommendationResponse recPojo : entrada.getRecommendationsPojo()) {
        Recommendation rec = new Recommendation();
        rec.setScore(recPojo.getScore());
        rec.setTechnology(key);

        Key<Recommendation> keyRecAtual = recService.add(rec);
        listKeyRec.add(keyRecAtual);
      }
    }

    entity.setRecommendations(listKeyRec);
    dao.update(entity);

    entrada.setId(entity.getId());
    entrada.setMensagem(ResponseMensagem.OK);

    return entrada;
  }

}
